// CRITERION: Generate and Execute Tests
const request = require('supertest');
const app = require('./server');
const chai = require('chai');
const expect = chai.expect;

// Mock Tokens for testing (replace with tokens generated by your running server)
// For a test, you might generate these tokens directly using jwt.sign in the test setup.
const ADMIN_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwMDAwMDAwMCwiZXhwIjoxNzAwMDAzNjAwfQ.FAKE_ADMIN_TOKEN'; 
const USER_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyMSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzAwMDAwMDAwfQ.FAKE_USER_TOKEN'; 

describe('SafeVault Security Tests', () => {

    it('1. Should deny access without a token (Authentication Check)', (done) => {
        request(app)
            .get('/api/vault/my-items')
            .expect(401)
            .end((err, res) => {
                expect(res.body.message).to.include('No token provided');
                done(err);
            });
    });

    it('2. Should allow access with a valid USER token', (done) => {
        request(app)
            .get('/api/vault/my-items')
            .set('Authorization', `Bearer ${USER_TOKEN}`)
            .expect(200)
            .end((err, res) => {
                // Assert that the user only gets their own items (Horizontal access check)
                expect(res.body).to.have.lengthOf(1); // User 2 owns 1 item in the mock data
                done(err);
            });
    });

    it('3. Should deny USER access to ADMIN endpoint (RBAC Check)', (done) => {
        request(app)
            .get('/api/vault/admin/all-data')
            .set('Authorization', `Bearer ${USER_TOKEN}`)
            .expect(403)
            .end((err, res) => {
                expect(res.body.message).to.include('Insufficient permissions');
                done(err);
            });
    });

    it('4. Should allow ADMIN access to ADMIN endpoint (RBAC Check)', (done) => {
        request(app)
            .get('/api/vault/admin/all-data')
            .set('Authorization', `Bearer ${ADMIN_TOKEN}`)
            .expect(200)
            .end((err, res) => {
                expect(res.body).to.have.lengthOf(3); // Admin can see all 3 mock items
                done(err);
            });
    });
});